AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Step Functions - State Machine

Parameters:
  PipelineName:
    Type: String
  SagerMakerRoleArn:
    Type: String
  WorkflowExecutionRoleArn:
    Type: String
  TargetEnv:
    Type: String

Resources:
  StateMachineComponent:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${PipelineName}-${TargetEnv}"
      DefinitionString: !Sub |-
        {
          "StartAt": "SageMaker pre-processing step",
          "States": {
            "SageMaker pre-processing step": {
              "Resource": "arn:aws:states:::sagemaker:createProcessingJob.sync",
              "Parameters": {
                "ProcessingJobName.$": "$$.Execution.Input['PreprocessingJobName']",
                "ProcessingInputs": [
                  {
                    "InputName": "input-data",
                    "AppManaged": false,
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['InputDataURL']",
                      "LocalPath": "/opt/ml/processing/input",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  },
                  {
                    "InputName": "code",
                    "AppManaged": false,
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['PreprocessingCodeURL']",
                      "LocalPath": "/opt/ml/processing/input/code",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  }
                ],
                "ProcessingOutputConfig": {
                  "Outputs": [
                    {
                      "OutputName": "train-baseline",
                      "AppManaged": false,
                      "S3Output": {
                        "S3Uri.$": "$$.Execution.Input['MonitorTrainOutputURL']",
                        "LocalPath": "/opt/ml/processing/profiling",
                        "S3UploadMode": "EndOfJob"
                      }
                    }
                  ]
                },
                "AppSpecification": {
                  "ImageUri": "342474125894.dkr.ecr.ap-southeast-1.amazonaws.com/mlmax-processing-monitor:latest",
                  "ContainerArguments": [
                    "--train-test-split-ratio",
                    "0.2",
                    "--mode",
                    "train"
                  ],
                  "ContainerEntrypoint": [
                    "python3",
                    "/opt/ml/processing/input/code/monitoring.py"
                  ]
                },
                "RoleArn": "${SagerMakerRoleArn}",
                "Environment": {
                  "mode": "python"
                },
                "ProcessingResources": {
                  "ClusterConfig": {
                    "InstanceCount": 16,
                    "InstanceType": "ml.m5.2xlarge",
                    "VolumeSizeInGB": 30
                  }
                },
                "StoppingCondition": {
                  "MaxRuntimeInSeconds": 3600
                }
              },
              "Type": "Task",
              "End": true,
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "ML Workflow failed": {
              "Cause": "SageMakerProcessingJobFailed",
              "Type": "Fail"
            }
          }
        }
      RoleArn: !Sub "${WorkflowExecutionRoleArn}"

Outputs:
  StateMachineComponentArn:
    Description: The step function ARN
    Value: !GetAtt StateMachineComponent.Arn
