AWSTemplateFormatVersion: 2010-09-09

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m5.xlarge
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  S3BucketName:
    Type: String
  EnvironmentName:
    Type: String
    Default: regulated-env
  Ami:
    Description: AMI id (default to the latest alinux2 for x64)
    Type: String
    Default: resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !ImportValue ExpVPCEndpointSecurityGroupId
      SubnetId: !ImportValue ExpPrivateSubnet1
      KeyName: !Ref KeyName
      ImageId: !Ref Ami
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 100
            VolumeType: gp3
            Iops: 600
            DeleteOnTermination: true
            Encrypted: true
            KmsKeyId: !ImportValue ExpCustomerKey

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref S3PolicyIL
        # Use managed policy
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess

  S3PolicyIL:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRWAccessToBucket
            Effect: Allow
            Action:
              - "s3:GetObject*"
              - "s3:PutObject*"
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}/*"
              - arn:aws:s3:::patch-baseline-snapshot-region/*
              - arn:aws:s3:::aws-ssm-region/*
          - Sid: AllowListBucket
            Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}"
          - Sid: AllowKMS
            Effect: Allow
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
              - "kms:GenerateDataKeyWithoutPlaintext"
              - "kms:ReEncrypt*"
              - "kms:CreateGrant"
            Resource: "*"
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
