AWSTemplateFormatVersion: 2010-09-09
Description: "SageMaker Notebook"

Parameters:
  S3BucketName:
    Type: String
    Default: regulated-bucket
  Username:
    Type: String
    Default: myname

Resources:
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      # NotebookInstanceName: !Ref Username
      InstanceType: "ml.t2.medium"
      RoleArn: !GetAtt SagemakerRole.Arn
      VolumeSizeInGB: 20
      DirectInternetAccess: Disabled
      KmsKeyId: !ImportValue ExpCustomerKey
      SecurityGroupIds:
        - !ImportValue ExpVPCEndpointSecurityGroup
      SubnetId: !ImportValue ExpPrivateSubnet1
      Tags:
        - Key: Name
          Value: !Ref Username

  SagemakerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Ref S3Policy
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess

  S3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRWAccessToBucket
            Effect: Allow
            Action:
              - "s3:GetObject*"
              - "s3:PutObject*"
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}/*"
          - Sid: AllowListBucket
            Effect: Allow
            Action:
              - "s3:ListBucket"
            Resource:
              - !Sub "arn:aws:s3:::${S3BucketName}"
          - Sid: AllowKMS
            Effect: Allow
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
              - "kms:Get*"
              - "kms:List*"
              - "kms:CreateGrant"
              - "kms:PutKeyPolicy"
              - "kms:RetireGrant"
              - "kms:RevokeGrant"
              - "kms:Verify"
            Resource: "*"

Outputs:
  BasicNotebookInstanceId:
    Value: !Ref NotebookInstance
