AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for AWS Step Functions - State Machine

# Added by script
Parameters:
  PipelineName:
    Type: String
  SagerMakerRoleArn:
    Type: String
  WorkflowExecutionRoleArn:
    Type: String
  TargetEnv:
    Type: String

Resources:
  StateMachineComponent:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "${PipelineName}-Inference-${TargetEnv}"
      DefinitionString: !Sub |-
        {
          "StartAt": "SageMaker pre-processing step",
          "States": {
            "SageMaker pre-processing step": {
              "Resource": "arn:aws:states:::sagemaker:createProcessingJob.sync",
              "Parameters": {
                "ProcessingJobName.$": "$$.Execution.Input['PreprocessingJobName']",
                "ProcessingInputs": [
                  {
                    "InputName": "input-1",
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['InputDataURL']",
                      "LocalPath": "/opt/ml/processing/input",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  },
                  {
                    "InputName": "code",
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['PreprocessingCodeURL']",
                      "LocalPath": "/opt/ml/processing/input/code",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  },
                  {
                    "InputName": "proc_model",
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['ProcModelS3']",
                      "LocalPath": "/opt/ml/processing/model",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  }
                ],
                "ProcessingOutputConfig": {
                  "Outputs": [
                    {
                      "OutputName": "test_data",
                      "S3Output": {
                        "S3Uri.$": "$$.Execution.Input['PreprocessedTestDataURL']",
                        "LocalPath": "/opt/ml/processing/test",
                        "S3UploadMode": "EndOfJob"
                      }
                    }
                  ]
                },
                "AppSpecification": {
                  "ImageUri": "121021644041.dkr.ecr.ap-southeast-1.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3",
                  "ContainerArguments": [
                    "--mode",
                    "infer"
                  ],
                  "ContainerEntrypoint": [
                    "python3",
                    "/opt/ml/processing/input/code/preprocessing.py"
                  ]
                },
                "RoleArn": "${SagerMakerRoleArn}",
                "ProcessingResources": {
                  "ClusterConfig": {
                    "InstanceCount": 1,
                    "InstanceType": "ml.m5.xlarge",
                    "VolumeSizeInGB": 30
                  }
                },
                "StoppingCondition": {
                  "MaxRuntimeInSeconds": 1200
                }
              },
              "Type": "Task",
              "Next": "SageMaker inference step",
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "SageMaker inference step": {
              "Resource": "arn:aws:states:::sagemaker:createProcessingJob.sync",
              "Parameters": {
                "ProcessingJobName.$": "$$.Execution.Input['InferenceJobName']",
                "ProcessingInputs": [
                  {
                    "InputName": "input-1",
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['PreprocessedTestDataURL']",
                      "LocalPath": "/opt/ml/processing/input",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  },
                  {
                    "InputName": "code",
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['InferenceCodeURL']",
                      "LocalPath": "/opt/ml/processing/input/code",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  },
                  {
                    "InputName": "model",
                    "S3Input": {
                      "S3Uri.$": "$$.Execution.Input['ModelS3']",
                      "LocalPath": "/opt/ml/processing/model",
                      "S3DataType": "S3Prefix",
                      "S3InputMode": "File",
                      "S3DataDistributionType": "FullyReplicated",
                      "S3CompressionType": "None"
                    }
                  }
                ],
                "ProcessingOutputConfig": {
                  "Outputs": [
                    {
                      "OutputName": "test_data",
                      "S3Output": {
                        "S3Uri.$": "$$.Execution.Input['OutputPathURL']",
                        "LocalPath": "/opt/ml/processing/test",
                        "S3UploadMode": "EndOfJob"
                      }
                    }
                  ]
                },
                "AppSpecification": {
                  "ImageUri": "121021644041.dkr.ecr.ap-southeast-1.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3",
                  "ContainerEntrypoint": [
                    "python3",
                    "/opt/ml/processing/input/code/inference.py"
                  ]
                },
                "RoleArn": "${SagerMakerRoleArn}",
                "ProcessingResources": {
                  "ClusterConfig": {
                    "InstanceCount": 1,
                    "InstanceType": "ml.m5.xlarge",
                    "VolumeSizeInGB": 30
                  }
                },
                "StoppingCondition": {
                  "MaxRuntimeInSeconds": 1200
                }
              },
              "Type": "Task",
              "End": true,
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.TaskFailed"
                  ],
                  "Next": "ML Workflow failed"
                }
              ]
            },
            "ML Workflow failed": {
              "Cause": "SageMakerProcessingJobFailed",
              "Type": "Fail"
            }
          }
        }
      RoleArn: !Sub "${WorkflowExecutionRoleArn}"
