AWSTemplateFormatVersion: '2010-09-09'
Description: Define the IAM roles.

Parameters:
  PipelineName:
    Type: String
  TargetEnv:
    Type: String
  PackageBucket:
    Type: String
  IsCreateSagemakerRole:
    Type: String

Conditions:
  CreateSagemakerRole: !Equals 
    - !Ref IsCreateSagemakerRole
    - 'yes'

Resources:
  # Define Step Function Role
  WorkflowExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: !Sub states.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: PassRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'iam:PassRole'
                Resource: "*"
                Condition:
                  StringEquals:
                    'iam:PassedToService': sagemaker.amazonaws.com
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:CreateProcessingJob'
                  - 'sagemaker:CreateTransformJob'
                  - 'sagemaker:DescribeTransformJob'
                  - 'sagemaker:StopTransformJob'
                  - 'sagemaker:CreateTrainingJob'
                  - 'sagemaker:DescribeTrainingJob'
                  - 'sagemaker:StopTrainingJob'
                  - 'sagemaker:CreateHyperParameterTuningJob'
                  - 'sagemaker:DescribeHyperParameterTuningJob'
                  - 'sagemaker:StopHyperParameterTuningJob'
                  - 'sagemaker:CreateModel'
                  - 'sagemaker:CreateEndpointConfig'
                  - 'sagemaker:CreateEndpoint'
                  - 'sagemaker:DeleteEndpointConfig'
                  - 'sagemaker:DeleteEndpoint'
                  - 'sagemaker:UpdateEndpoint'
                  - 'sagemaker:ListTags'
                  - 'lambda:InvokeFunction'
                  - 'sqs:SendMessage'
                  - 'sns:Publish'
                  - 'ecs:RunTask'
                  - 'ecs:StopTask'
                  - 'ecs:DescribeTasks'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'batch:SubmitJob'
                  - 'batch:DescribeJobs'
                  - 'batch:TerminateJob'
                  - 'glue:StartJobRun'
                  - 'glue:GetJobRun'
                  - 'glue:GetJobRuns'
                  - 'glue:BatchStopJobRun'
                Resource: '*'
        - PolicyName: StatesStartExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "states:*"
                Resource: "*"
        - PolicyName: StatesAccessEventsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "events:*"
                Resource: "*"

  # Define SageMaker Execution Role
  SagerMakerRole:
    Condition: CreateSagemakerRole
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${PipelineName}-SageMakerRole-${TargetEnv}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      Path: /
      Policies:
        - PolicyName: CrossAccountS3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowRWAccessToBucket
                Effect: Allow
                Action:
                  - "s3:Delete*"
                  - "s3:Put*"
                  - "s3:Get*"
                  - "s3:List*"
                  - "s3:Create*"
                  - "s3:Head*"
                Resource:
                  - !Sub "arn:aws:s3:::${PackageBucket}"
                  - !Sub "arn:aws:s3:::${PackageBucket}/*"
              - Effect: Allow
                Action:
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:ReEncrypt*"
                  - "kms:GenerateDataKey*"
                  - "kms:DescribeKey" 
                Resource: "*"

Outputs:
  WorkflowExecutionRoleArn:
    Description: Training Pipeline Step Function Execution Role ARN
    Value: !GetAtt WorkflowExecutionRole.Arn
  SagerMakerRoleArn:
    Description: SageMaker ExecutionRole ARN
    Value: !GetAtt SagerMakerRole.Arn
    Condition: CreateSagemakerRole
